/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-01-27 10:21:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/E:/enter_workSpring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mySpring/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/board/../includes/footer.jsp", Long.valueOf(1643278209533L));
    _jspx_dependants.put("jar:file:/E:/enter_workSpring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mySpring/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/board/../includes/header.jsp", Long.valueOf(1643278209534L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.2.10.RELEASE.jar", Long.valueOf(1642637576721L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1640322152836L));
    _jspx_dependants.put("jar:file:/E:/enter_workSpring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mySpring/WEB-INF/lib/spring-security-taglibs-5.2.10.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1618212972000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>SB Admin 2 - Bootstrap Admin Theme</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"/resources/vendor/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- MetisMenu CSS -->\r\n");
      out.write("<link href=\"/resources/vendor/metisMenu/metisMenu.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- DataTables CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"/resources/vendor/datatables-plugins/dataTables.bootstrap.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- DataTables Responsive CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"/resources/vendor/datatables-responsive/dataTables.responsive.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"/resources/dist/css/sb-admin-2.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom Fonts -->\r\n");
      out.write("<link href=\"/resources/vendor/font-awesome/css/font-awesome.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Navigation -->\r\n");
      out.write("		<nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\"\r\n");
      out.write("			style=\"margin-bottom: 0\">\r\n");
      out.write("			<div class=\"navbar-header\">\r\n");
      out.write("				<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("					data-target=\".navbar-collapse\">\r\n");
      out.write("					<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("						class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("						class=\"icon-bar\"></span>\r\n");
      out.write("				</button>\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"index.html\">SB Admin v2.0</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /.navbar-header -->\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"nav navbar-top-links navbar-right\">\r\n");
      out.write("				<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("					data-toggle=\"dropdown\" href=\"#\"> <i\r\n");
      out.write("						class=\"fa fa-envelope fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"dropdown-menu dropdown-messages\">\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<strong>John Smith</strong> <span class=\"pull-right text-muted\">\r\n");
      out.write("										<em>Yesterday</em>\r\n");
      out.write("									</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>Lorem ipsum dolor sit amet, consectetur adipiscing\r\n");
      out.write("									elit. Pellentesque eleifend...</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<strong>John Smith</strong> <span class=\"pull-right text-muted\">\r\n");
      out.write("										<em>Yesterday</em>\r\n");
      out.write("									</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>Lorem ipsum dolor sit amet, consectetur adipiscing\r\n");
      out.write("									elit. Pellentesque eleifend...</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<strong>John Smith</strong> <span class=\"pull-right text-muted\">\r\n");
      out.write("										<em>Yesterday</em>\r\n");
      out.write("									</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>Lorem ipsum dolor sit amet, consectetur adipiscing\r\n");
      out.write("									elit. Pellentesque eleifend...</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a class=\"text-center\" href=\"#\"> <strong>Read\r\n");
      out.write("									All Messages</strong> <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul> <!-- /.dropdown-messages --></li>\r\n");
      out.write("				<!-- /.dropdown -->\r\n");
      out.write("				<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("					data-toggle=\"dropdown\" href=\"#\"> <i class=\"fa fa-tasks fa-fw\"></i>\r\n");
      out.write("						<i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"dropdown-menu dropdown-tasks\">\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p>\r\n");
      out.write("										<strong>Task 1</strong> <span class=\"pull-right text-muted\">40%\r\n");
      out.write("											Complete</span>\r\n");
      out.write("									</p>\r\n");
      out.write("									<div class=\"progress progress-striped active\">\r\n");
      out.write("										<div class=\"progress-bar progress-bar-success\"\r\n");
      out.write("											role=\"progressbar\" aria-valuenow=\"40\" aria-valuemin=\"0\"\r\n");
      out.write("											aria-valuemax=\"100\" style=\"width: 40%\">\r\n");
      out.write("											<span class=\"sr-only\">40% Complete (success)</span>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p>\r\n");
      out.write("										<strong>Task 2</strong> <span class=\"pull-right text-muted\">20%\r\n");
      out.write("											Complete</span>\r\n");
      out.write("									</p>\r\n");
      out.write("									<div class=\"progress progress-striped active\">\r\n");
      out.write("										<div class=\"progress-bar progress-bar-info\" role=\"progressbar\"\r\n");
      out.write("											aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\"\r\n");
      out.write("											style=\"width: 20%\">\r\n");
      out.write("											<span class=\"sr-only\">20% Complete</span>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p>\r\n");
      out.write("										<strong>Task 3</strong> <span class=\"pull-right text-muted\">60%\r\n");
      out.write("											Complete</span>\r\n");
      out.write("									</p>\r\n");
      out.write("									<div class=\"progress progress-striped active\">\r\n");
      out.write("										<div class=\"progress-bar progress-bar-warning\"\r\n");
      out.write("											role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\"\r\n");
      out.write("											aria-valuemax=\"100\" style=\"width: 60%\">\r\n");
      out.write("											<span class=\"sr-only\">60% Complete (warning)</span>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<p>\r\n");
      out.write("										<strong>Task 4</strong> <span class=\"pull-right text-muted\">80%\r\n");
      out.write("											Complete</span>\r\n");
      out.write("									</p>\r\n");
      out.write("									<div class=\"progress progress-striped active\">\r\n");
      out.write("										<div class=\"progress-bar progress-bar-danger\"\r\n");
      out.write("											role=\"progressbar\" aria-valuenow=\"80\" aria-valuemin=\"0\"\r\n");
      out.write("											aria-valuemax=\"100\" style=\"width: 80%\">\r\n");
      out.write("											<span class=\"sr-only\">80% Complete (danger)</span>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a class=\"text-center\" href=\"#\"> <strong>See\r\n");
      out.write("									All Tasks</strong> <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul> <!-- /.dropdown-tasks --></li>\r\n");
      out.write("				<!-- /.dropdown -->\r\n");
      out.write("				<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("					data-toggle=\"dropdown\" href=\"#\"> <i class=\"fa fa-bell fa-fw\"></i>\r\n");
      out.write("						<i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"dropdown-menu dropdown-alerts\">\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<i class=\"fa fa-comment fa-fw\"></i> New Comment <span\r\n");
      out.write("										class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<i class=\"fa fa-twitter fa-fw\"></i> 3 New Followers <span\r\n");
      out.write("										class=\"pull-right text-muted small\">12 minutes ago</span>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<i class=\"fa fa-envelope fa-fw\"></i> Message Sent <span\r\n");
      out.write("										class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<i class=\"fa fa-tasks fa-fw\"></i> New Task <span\r\n");
      out.write("										class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a href=\"#\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<i class=\"fa fa-upload fa-fw\"></i> Server Rebooted <span\r\n");
      out.write("										class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("								</div>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a class=\"text-center\" href=\"#\"> <strong>See\r\n");
      out.write("									All Alerts</strong> <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul> <!-- /.dropdown-alerts --></li>\r\n");
      out.write("				<!-- /.dropdown -->\r\n");
      out.write("				<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("					data-toggle=\"dropdown\" href=\"#\"> <i class=\"fa fa-user fa-fw\"></i>\r\n");
      out.write("						<i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"dropdown-menu dropdown-user\">\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-user fa-fw\"></i> User\r\n");
      out.write("								Profile</a></li>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-gear fa-fw\"></i> Settings</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"divider\"></li>\r\n");
      out.write("						<li><a href=\"login.html\"><i class=\"fa fa-sign-out fa-fw\"></i>\r\n");
      out.write("								Logout</a></li>\r\n");
      out.write("					</ul> <!-- /.dropdown-user --></li>\r\n");
      out.write("				<!-- /.dropdown -->\r\n");
      out.write("			</ul>\r\n");
      out.write("			<!-- /.navbar-top-links -->\r\n");
      out.write("\r\n");
      out.write("			<div class=\"navbar-default sidebar\" role=\"navigation\">\r\n");
      out.write("				<div class=\"sidebar-nav navbar-collapse\">\r\n");
      out.write("					<ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("						<li class=\"sidebar-search\">\r\n");
      out.write("							<div class=\"input-group custom-search-form\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
      out.write("								<span class=\"input-group-btn\">\r\n");
      out.write("									<button class=\"btn btn-default\" type=\"button\">\r\n");
      out.write("										<i class=\"fa fa-search\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("								</span>\r\n");
      out.write("							</div> <!-- /input-group -->\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a href=\"index.html\"><i class=\"fa fa-dashboard fa-fw\"></i>\r\n");
      out.write("								Dashboard</a></li>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-bar-chart-o fa-fw\"></i>\r\n");
      out.write("								Charts<span class=\"fa arrow\"></span></a>\r\n");
      out.write("							<ul class=\"nav nav-second-level\">\r\n");
      out.write("								<li><a href=\"flot.html\">Flot Charts</a></li>\r\n");
      out.write("								<li><a href=\"morris.html\">Morris.js Charts</a></li>\r\n");
      out.write("							</ul> <!-- /.nav-second-level --></li>\r\n");
      out.write("						<li><a href=\"tables.html\"><i class=\"fa fa-table fa-fw\"></i>\r\n");
      out.write("								Tables</a></li>\r\n");
      out.write("						<li><a href=\"forms.html\"><i class=\"fa fa-edit fa-fw\"></i>\r\n");
      out.write("								Forms</a></li>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-wrench fa-fw\"></i> UI\r\n");
      out.write("								Elements<span class=\"fa arrow\"></span></a>\r\n");
      out.write("							<ul class=\"nav nav-second-level\">\r\n");
      out.write("								<li><a href=\"panels-wells.html\">Panels and Wells</a></li>\r\n");
      out.write("								<li><a href=\"buttons.html\">Buttons</a></li>\r\n");
      out.write("								<li><a href=\"notifications.html\">Notifications</a></li>\r\n");
      out.write("								<li><a href=\"typography.html\">Typography</a></li>\r\n");
      out.write("								<li><a href=\"icons.html\"> Icons</a></li>\r\n");
      out.write("								<li><a href=\"grid.html\">Grid</a></li>\r\n");
      out.write("							</ul> <!-- /.nav-second-level --></li>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-sitemap fa-fw\"></i>\r\n");
      out.write("								Multi-Level Dropdown<span class=\"fa arrow\"></span></a>\r\n");
      out.write("							<ul class=\"nav nav-second-level\">\r\n");
      out.write("								<li><a href=\"#\">Second Level Item</a></li>\r\n");
      out.write("								<li><a href=\"#\">Second Level Item</a></li>\r\n");
      out.write("								<li><a href=\"#\">Third Level <span class=\"fa arrow\"></span></a>\r\n");
      out.write("									<ul class=\"nav nav-third-level\">\r\n");
      out.write("										<li><a href=\"#\">Third Level Item</a></li>\r\n");
      out.write("										<li><a href=\"#\">Third Level Item</a></li>\r\n");
      out.write("										<li><a href=\"#\">Third Level Item</a></li>\r\n");
      out.write("										<li><a href=\"#\">Third Level Item</a></li>\r\n");
      out.write("									</ul> <!-- /.nav-third-level --></li>\r\n");
      out.write("							</ul> <!-- /.nav-second-level --></li>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"fa fa-files-o fa-fw\"></i>\r\n");
      out.write("								Sample Pages<span class=\"fa arrow\"></span></a>\r\n");
      out.write("							<ul class=\"nav nav-second-level\">\r\n");
      out.write("								<li><a href=\"blank.html\">Blank Page</a></li>\r\n");
      out.write("								<li><a href=\"login.html\">Login Page</a></li>\r\n");
      out.write("							</ul> <!-- /.nav-second-level --></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- /.sidebar-collapse -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /.navbar-static-side -->\r\n");
      out.write("		</nav>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("    <script src=\"/resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("    <script src=\"/resources/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Metis Menu Plugin JavaScript -->\r\n");
      out.write("    <script src=\"/resources/vendor/metisMenu/metisMenu.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- DataTables JavaScript -->\r\n");
      out.write("    <script src=\"/resources/vendor/datatables/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/vendor/datatables-plugins/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/vendor/datatables-responsive/dataTables.responsive.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Theme JavaScript -->\r\n");
      out.write("    <script src=\"/resources/dist/js/sb-admin-2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page-Level Demo Scripts - Tables - Use for reference -->\r\n");
      out.write("    <script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $('#dataTables-example').DataTable({\r\n");
      out.write("            responsive: true\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write(".uploadResult {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uploadResult ul {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-flow: row;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uploadResult ul li {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uploadResult ul li img {\r\n");
      out.write("	width: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uploadResult ul li span {\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"page-wrapper\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-12\">\r\n");
      out.write("				<h1 class=\"page-header\">Board Modify Page</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /.col-lg-12 -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- /.row -->\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-12\">\r\n");
      out.write("				<div class=\"panel panel-default\">\r\n");
      out.write("					<div class=\"panel-heading\">게시글 수정</div>\r\n");
      out.write("					<!-- /.panel-heading -->\r\n");
      out.write("					<div class=\"panel-body\">\r\n");
      out.write("						<form role=\"form\" action=\"/board/modify\" method=\"post\">\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label>BNO</label>\r\n");
      out.write("								<input class=\"form-control\" name=\"bno\" value='");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("' readonly=\"readonly\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label>TITLE</label>\r\n");
      out.write("								<input class=\"form-control\" name=\"title\" value='");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label>CONTENT</label>\r\n");
      out.write("								<textarea class=\"form-control\" rows=\"3\" name=\"content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label>WRITER</label>\r\n");
      out.write("								<input class=\"form-control\" name=\"writer\" value='");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("' readonly=\"readonly\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label>REGDATE</label>\r\n");
      out.write("								<input class=\"form-control\" name=\"regDate\" value='");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("' readonly=\"readonly\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label>UPDATEDATE</label>\r\n");
      out.write("								<input class=\"form-control\" name=\"updateDate\" value='");
      if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_page_context))
        return;
      out.write("' readonly=\"readonly\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 페이지 처리 -->\r\n");
      out.write("							<input type=\"hidden\" name=\"pageNum\" value='");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("							<input type=\"hidden\" name=\"amount\" value='");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("							\r\n");
      out.write("							<!-- 검색 조건 및 키워드 처리 -->\r\n");
      out.write("							<input type=\"hidden\" name=\"type\" value='");
      if (_jspx_meth_c_005fout_005f5(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("							<input type=\"hidden\" name=\"keyword\" value='");
      if (_jspx_meth_c_005fout_005f6(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("							\r\n");
      out.write("							<input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("							<!-- \r\n");
      out.write("							");
      if (_jspx_meth_sec_005fauthentication_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							\r\n");
      out.write("							");
      if (_jspx_meth_sec_005fauthentication_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							 -->\r\n");
      out.write("							<button type=\"submit\" data-oper='modify' class=\"btn btn-outline btn-primary\" onclick=\"location.href='/board/modify?bno=");
      if (_jspx_meth_c_005fout_005f8(_jspx_page_context))
        return;
      out.write("'\">Modify</button>\r\n");
      out.write("							<button type=\"submit\" data-oper='remove' class=\"btn btn-outline btn-danger\" onclick=\"location.href='/board/list'\">Remove</button>\r\n");
      out.write("							<button type=\"submit\" data-oper='list' class=\"btn btn-outline btn-success\" onclick=\"location.href='/board/list'\">List</button>\r\n");
      out.write("						</form>\r\n");
      out.write("						<!-- /.table-responsive -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- /.panel-body -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- /.panel -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- /.col-lg-12 -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"panel panel-default\">\r\n");
      out.write("			<div class=\"panel-heading\">\r\n");
      out.write("				<i class=\"fa fa-comments fa-fw\"></i> File Attach\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"panel-body\">\r\n");
      out.write("				<div class=\"form-group uploadDiv\">\r\n");
      out.write("					<input type=\"file\" name=\"uploadFile\" multiple>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 첨부파일 띄우기 -->\r\n");
      out.write("				<div class=\"uploadResult\">\r\n");
      out.write("					<ul></ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- 이미지 크게 보이게 -->\r\n");
      out.write("				<div class=\"bigPictureWrapper\">\r\n");
      out.write("					<div class=\"bigPicture\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"panel-footer\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /#page-wrapper -->\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(document).ready(function() {\r\n");
      out.write("			var formObj = $(\"form\");\r\n");
      out.write("			\r\n");
      out.write("			$('button').on(\"click\", function(e) {\r\n");
      out.write("				e.preventDefault();\r\n");
      out.write("				var operation = $(this).data(\"oper\");\r\n");
      out.write("				console.log(operation);\r\n");
      out.write("				if (operation === 'remove') {\r\n");
      out.write("					formObj.attr(\"action\", \"/board/remove\");\r\n");
      out.write("				} else if (operation === 'list') {\r\n");
      out.write("					// move to list\r\n");
      out.write("					/* self.location = \"/board/list\";\r\n");
      out.write("					return; */\r\n");
      out.write("					formObj.attr(\"action\", \"/board/list\").attr(\"method\", \"get\");\r\n");
      out.write("					\r\n");
      out.write("					// 페이지 처리\r\n");
      out.write("					// 잠시 보관\r\n");
      out.write("					var pageNumTag = $(\"input[name='pageNum']\").clone();\r\n");
      out.write("					var amountTag = $(\"input[name='amount']\").clone();\r\n");
      out.write("					var typeTag = $(\"input[name='type']\").clone();\r\n");
      out.write("					var keywordTag = $(\"input[name='keyword']\").clone();\r\n");
      out.write("					\r\n");
      out.write("					formObj.empty(); // 제거\r\n");
      out.write("					\r\n");
      out.write("					// 필요한 태그들 추가\r\n");
      out.write("					formObj.append(pageNumTag);\r\n");
      out.write("					formObj.append(amountTag);\r\n");
      out.write("					formObj.append(typeTag);\r\n");
      out.write("					formObj.append(keywordTag);\r\n");
      out.write("				} else if (operation === 'modify') {\r\n");
      out.write("					console.log(\"submit clicked\");\r\n");
      out.write("					var str = \"\";\r\n");
      out.write("					$(\".uploadResult ul li\").each(function(i, obj) { // 첨부파일 정보 전송\r\n");
      out.write("						var jobj = $(obj);\r\n");
      out.write("						console.dir(jobj);\r\n");
      out.write("						str += \"<input type='hidden' name='attachList[\"+i+\"].fileName' value='\"+jobj.data(\"filename\")+\"'>\";\r\n");
      out.write("						str += \"<input type='hidden' name='attachList[\"+i+\"].uuid' value='\"+jobj.data(\"uuid\")+\"'>\";\r\n");
      out.write("						str += \"<input type='hidden' name='attachList[\"+i+\"].uploadPath' value='\"+jobj.data(\"path\")+\"'>\";\r\n");
      out.write("						str += \"<input type='hidden' name='attachList[\"+i+\"].fileType' value='\"+jobj.data(\"type\")+\"'>\";\r\n");
      out.write("					});\r\n");
      out.write("					formObj.append(str);\r\n");
      out.write("				}\r\n");
      out.write("				formObj.submit();\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			// 첨부파일 데이터 보여주기\r\n");
      out.write("			// BoardController의 getAttachList로 bno 보내서 arr(첨부파일 리스트) 받아서 출력 \r\n");
      out.write("			var bno = '");
      if (_jspx_meth_c_005fout_005f9(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("			$.getJSON(\"/board/getAttachList\", {bno:bno}, function(arr) { // url, data, success\r\n");
      out.write("				console.log(arr);\r\n");
      out.write("				var str = \"\";\r\n");
      out.write("				$(arr).each(function(i, obj) {\r\n");
      out.write("					if(!obj.fileType) { // 이미지가 아닌 경우\r\n");
      out.write("						\r\n");
      out.write("						var fileCallPath = encodeURIComponent(obj.uploadPath + \"/\" + obj.uuid + \"_\" + obj.fileName);\r\n");
      out.write("						str += \"<li data-path='\"+obj.uploadPath+\"' data-uuid='\"+obj.uuid+\"' data-filename='\"+obj.fileName+\"' data-type='\"+obj.fileType+\"'><div>\";\r\n");
      out.write("						str += \"<span>\" + obj.fileName + \"</span>\";\r\n");
      out.write("						str += \"<button type='button' data-file=\\'\"+fileCallPath+\"\\' data-type='file' class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button><br>\";\r\n");
      out.write("						str += \"<img src='/resources/images/attach.png'>\";\r\n");
      out.write("						str += \"</div></li>\";\r\n");
      out.write("					} else {\r\n");
      out.write("						\r\n");
      out.write("						// 썸네일 나오게 처리\r\n");
      out.write("						var fileCallPath = encodeURIComponent(obj.uploadPath +  \"/s_\" + obj.uuid + \"_\" + obj.fileName);\r\n");
      out.write("						var originPath = obj.uploadPath + \"/\" + obj.uuid + \"_\" + obj.fileName;\r\n");
      out.write("						console.log(\"originPath1 : \" + originPath);\r\n");
      out.write("						originPath = originPath.replace(new RegExp(/\\\\/g), \"/\"); // \\를 /로 통일\r\n");
      out.write("						console.log(\"originPath2 : \" + originPath);\r\n");
      out.write("						str += \"<li data-path='\"+obj.uploadPath+\"' data-uuid='\"+obj.uuid+\"' data-filename='\"+obj.fileName+\"' data-type='\"+obj.fileType+\"'><div>\";\r\n");
      out.write("						str += \"<span>\" + obj.fileName + \"</span>\";\r\n");
      out.write("						str += \"<button type='button' data-file=\\'\"+fileCallPath+\"\\' data-type='file' class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button><br>\";\r\n");
      out.write("						str += \"<img src='/display?fileName=\" + fileCallPath + \"'>\";\r\n");
      out.write("						str += \"</div></li>\";\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("				$(\".uploadResult ul\").html(str);\r\n");
      out.write("			}); // getJSON\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			// 첨부파일 삭제\r\n");
      out.write("			// 버튼 클릭시 삭제\r\n");
      out.write("			$(\".uploadResult\").on(\"click\", \"button\", function(e) {\r\n");
      out.write("				alert(\"delete file\");\r\n");
      out.write("				\r\n");
      out.write("				if(confirm(\"이 파일을 삭제하시겠습니까?\")) {\r\n");
      out.write("					var targetLi = $(this).closest(\"li\");\r\n");
      out.write("					targetLi.remove();									\r\n");
      out.write("				}	\r\n");
      out.write("			}); // uploadResult click event\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			// 첨부파일 추가\r\n");
      out.write("			// 정규식을 이용해서 파일 확장자 체크\r\n");
      out.write("			var regex = new RegExp(\"(.*?)\\.(exe|sh|zip|alz)$\");\r\n");
      out.write("			var maxSize = 5242880;\r\n");
      out.write("			function checkExtension(fileName, fileSize) {\r\n");
      out.write("				if(fileSize >= maxSize) {\r\n");
      out.write("					alert(\"파일 크기 초과\");\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("				if(regex.test(fileName)) {\r\n");
      out.write("					alert(\"해당 종류의 파일은 업로드 할 수 없음\");\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("				return true;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			// 업로드 전에 <input type=\"file\"> 객체가 포함된 <div> 복사\r\n");
      out.write("			var cloneObj = $(\".uploadDiv\").clone();\r\n");
      out.write("			\r\n");
      out.write("			// <input type=\"file\"> 내용이 변경되는 것을 감지해서 무조건 업로드 처리\r\n");
      out.write("			//$(document).on('change', \"input[type='file']\", function(e) {\r\n");
      out.write("				var csrfHeaderName = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("				var csrfTokenValue = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("			$(\"input[type='file']\").change(function(e) {\r\n");
      out.write("				// 파일 업로드\r\n");
      out.write("				// ajax 이용하는 경우에는 FormData 객체 이용 (form 태그와 같은 역할)\r\n");
      out.write("				var formData = new FormData();\r\n");
      out.write("				var inputFile = $(\"input[name='uploadFile']\");\r\n");
      out.write("				var files = inputFile[0].files;\r\n");
      out.write("				console.log(files);\r\n");
      out.write("				\r\n");
      out.write("				// add filedata to formdata\r\n");
      out.write("				for(var i = 0; i < files.length; i++) {\r\n");
      out.write("					if(!checkExtension(files[i].name, files[i].size)) { // 파일 확장자 체크\r\n");
      out.write("						return false;\r\n");
      out.write("					}\r\n");
      out.write("					formData.append(\"uploadFile\", files[i]);\r\n");
      out.write("				}\r\n");
      out.write("				console.log(\"files.length : \" + files.length);\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : '/uploadAjaxAction',\r\n");
      out.write("					processData : false, // 전달할 데이터를 query string을 만들지 말 것\r\n");
      out.write("					contentType : false,\r\n");
      out.write("					data : formData, // 전달할 데이터\r\n");
      out.write("					type : 'POST',\r\n");
      out.write("					dataType: 'json', // 데이터 타입: json\r\n");
      out.write("					beforeSend: function(xhr) {\r\n");
      out.write("						xhr.setRequestHeader(csrfHeaderName, csrfTokenValue);\r\n");
      out.write("					},\r\n");
      out.write("					success : function (result) {\r\n");
      out.write("						alert('Uploaded');\r\n");
      out.write("						console.log(result);\r\n");
      out.write("						showUploadedFile(result); // json 형태의 업로드 결과를 인자로 줌				\r\n");
      out.write("						//$(\".uploadDiv\").html(cloneObj.html()); // 업로드 성공 후 초기 상태로 복원\r\n");
      out.write("					}\r\n");
      out.write("				}); // $.ajax\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			var uploadResult = $(\".uploadResult ul\");\r\n");
      out.write("			function showUploadedFile(uploadResultArr) {\r\n");
      out.write("				if(!uploadResultArr || uploadResultArr.length == 0) {\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				var str = \"\";\r\n");
      out.write("				$(uploadResultArr).each(function(i, obj) {\r\n");
      out.write("					if(!obj.image) { // 이미지가 아닌 경우\r\n");
      out.write("						\r\n");
      out.write("						var fileCallPath = encodeURIComponent(obj.uploadPath + \"/\" + obj.uuid + \"_\" + obj.fileName);\r\n");
      out.write("						str += \"<li data-path='\"+obj.uploadPath+\"' data-uuid='\"+obj.uuid+\"' data-filename='\"+obj.fileName+\"' data-type='\"+obj.image+\"'><div>\";\r\n");
      out.write("						str += \"<span>\" + obj.fileName + \"</span>\";\r\n");
      out.write("						str += \"<button type='button' data-file=\\'\"+fileCallPath+\"\\' data-type='file' class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button><br>\";\r\n");
      out.write("						str += \"<img src='/resources/images/attach.png'>\";\r\n");
      out.write("						str += \"</div></li>\";\r\n");
      out.write("					} else {\r\n");
      out.write("						\r\n");
      out.write("						// 썸네일 나오게 처리\r\n");
      out.write("						var fileCallPath = encodeURIComponent(obj.uploadPath +  \"/s_\" + obj.uuid + \"_\" + obj.fileName);\r\n");
      out.write("						var originPath = obj.uploadPath + \"/\" + obj.uuid + \"_\" + obj.fileName;\r\n");
      out.write("						console.log(\"originPath1 : \" + originPath);\r\n");
      out.write("						originPath = originPath.replace(new RegExp(/\\\\/g), \"/\"); // \\를 /로 통일\r\n");
      out.write("						console.log(\"originPath2 : \" + originPath);\r\n");
      out.write("						str += \"<li data-path='\"+obj.uploadPath+\"' data-uuid='\"+obj.uuid+\"' data-filename='\"+obj.fileName+\"' data-type='\"+obj.image+\"'><div>\";\r\n");
      out.write("						str += \"<span>\" + obj.fileName + \"</span>\";\r\n");
      out.write("						str += \"<button type='button' data-file=\\'\"+fileCallPath+\"\\' data-type='image' class='btn btn-warning btn-circle'><i class='fa fa-times'></i></button><br>\";\r\n");
      out.write("						str += \"<img src='/display?fileName=\" + fileCallPath + \"'>\";\r\n");
      out.write("						str += \"</div></li>\";\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("				uploadResult.append(str); // 요소 추가 (<li> 추가)\r\n");
      out.write("			} // showUploadedFile\r\n");
      out.write("			\r\n");
      out.write("			// 버튼 클릭시 삭제\r\n");
      out.write("			$(\".uploadResult\").on(\"click\", \"button\", function(e) {\r\n");
      out.write("				alert(\"delete file\");\r\n");
      out.write("				\r\n");
      out.write("				var targetFile = $(this).data(\"file\");\r\n");
      out.write("				var type = $(this).data(\"type\");\r\n");
      out.write("				var targetLi = $(this).closest(\"li\");\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: '/deleteFile',\r\n");
      out.write("					data: {fileName: targetFile, type: type},\r\n");
      out.write("					dataType: 'text',\r\n");
      out.write("					type: 'post',\r\n");
      out.write("					beforeSend: function(xhr) {\r\n");
      out.write("						xhr.setRequestHeader(csrfHeaderName, csrfTokenValue);\r\n");
      out.write("					},\r\n");
      out.write("					success: function(result) {\r\n");
      out.write("						alert(result);\r\n");
      out.write("						targetLi.remove(); // li 삭제\r\n");
      out.write("					}\r\n");
      out.write("				}); // $.ajax\r\n");
      out.write("			}); // uploadResult\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/board/modify.jsp(57,54) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/board/modify.jsp(61,56) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/views/board/modify.jsp(69,57) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.writer}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/views/board/modify.jsp(73,58) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.regDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/board/modify.jsp(73,58) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy/MM/dd (E)");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f1.setParent(null);
      // /WEB-INF/views/board/modify.jsp(77,61) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.updateDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/board/modify.jsp(77,61) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setPattern("yyyy/MM/dd (E)");
      int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      _jspx_th_fmt_005fformatDate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /WEB-INF/views/board/modify.jsp(80,50) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.pageNum}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent(null);
      // /WEB-INF/views/board/modify.jsp(81,49) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.amount}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f5_reused = false;
    try {
      _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f5.setParent(null);
      // /WEB-INF/views/board/modify.jsp(84,47) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.type}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
      if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      _jspx_th_c_005fout_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f6_reused = false;
    try {
      _jspx_th_c_005fout_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f6.setParent(null);
      // /WEB-INF/views/board/modify.jsp(85,50) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.keyword}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f6 = _jspx_th_c_005fout_005f6.doStartTag();
      if (_jspx_th_c_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
      _jspx_th_c_005fout_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent(null);
      // /WEB-INF/views/board/modify.jsp(89,7) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal");
      // /WEB-INF/views/board/modify.jsp(89,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setVar("pinfo");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/board/modify.jsp(90,8) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("								");
        if (_jspx_meth_c_005fif_005f0(_jspx_th_sec_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("							");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f0);
      // /WEB-INF/views/board/modify.jsp(91,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pinfo.username eq board.writer}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<button type=\"submit\" data-oper='modify' class=\"btn btn-outline btn-primary\" onclick=\"location.href='/board/modify?bno=");
          if (_jspx_meth_c_005fout_005f7(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("'\">Modify</button>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f7_reused = false;
    try {
      _jspx_th_c_005fout_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/board/modify.jsp(92,128) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f7 = _jspx_th_c_005fout_005f7.doStartTag();
      if (_jspx_th_c_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
      _jspx_th_c_005fout_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f1 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f1.setParent(null);
      // /WEB-INF/views/board/modify.jsp(96,7) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f1.setProperty("principal");
      // /WEB-INF/views/board/modify.jsp(96,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f1.setVar("pinfo");
      int _jspx_eval_sec_005fauthentication_005f1 = _jspx_th_sec_005fauthentication_005f1.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f1);
      _jspx_th_sec_005fauthentication_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/board/modify.jsp(97,8) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("								");
        if (_jspx_meth_c_005fif_005f1(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("							");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/board/modify.jsp(98,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pinfo.username eq board.writer}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<button type=\"submit\" data-oper='remove' class=\"btn btn-outline btn-danger\" onclick=\"location.href='/board/list'\">Remove</button>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f8 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f8_reused = false;
    try {
      _jspx_th_c_005fout_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f8.setParent(null);
      // /WEB-INF/views/board/modify.jsp(103,126) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f8.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f8 = _jspx_th_c_005fout_005f8.doStartTag();
      if (_jspx_th_c_005fout_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f8);
      _jspx_th_c_005fout_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f9 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f9_reused = false;
    try {
      _jspx_th_c_005fout_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f9.setParent(null);
      // /WEB-INF/views/board/modify.jsp(191,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f9.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f9 = _jspx_th_c_005fout_005f9.doStartTag();
      if (_jspx_th_c_005fout_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f9);
      _jspx_th_c_005fout_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f9_reused);
    }
    return false;
  }
}
